# -*- coding: utf-8 -*-
"""SL_App1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqsPq-8FWDP_WU1Qt721lUq9g_XnW2FI
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Set page title
st.set_page_config(page_title='Line Chart Example')

# Define function to read CSV file and return a DataFrame
def load_data(file):
    df = pd.read_csv(file)
    return df

# Create file uploader
uploaded_file = st.file_uploader('Choose a CSV file', type='csv')

# If a file was uploaded, load it into a DataFrame
if uploaded_file is not None:
    df = load_data(uploaded_file)

    # Display the DataFrame in a table
    st.write('DataFrame:')
    st.write(df)

    # Create line chart using Plotly Express
    fig = px.line(df, x='date', y='value', title='Line Chart')
    st.plotly_chart(fig)